<?xml version="1.0" encoding="utf-8"?><Database Name="FaceRecog" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KURO\SQLEXPRESS;Initial Catalog=FaceRecog;Integrated Security=True" SettingsObjectName="CameraDiemDanh.Properties.Settings" SettingsPropertyName="FaceRecogConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.[Procedure]" Method="Procedure">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="TenKhoa" Parameter="tenKhoa" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[Procedure]" Method="Procedure1">
    <Parameter Name="TenKhoa" Parameter="tenKhoa" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.[Delete]" Method="Delete">
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Delete2" Method="Delete2">
    <Parameter Name="TenMH" Parameter="tenMH" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Delete3" Method="Delete3">
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>